
SHIPTYPE_LIST=[
    {"id": 0, "label": "Not available"},
    {"id": 1, "label": "Reserved for future use"},
    {"id": 2, "label": "Reserved for future use"},
    {"id": 3, "label": "Reserved for future use"},
    {"id": 4, "label": "Reserved for future use"},
    {"id": 5, "label": "Reserved for future use"},
    {"id": 6, "label": "Reserved for future use"},
    {"id": 7, "label": "Reserved for future use"},
    {"id": 8, "label": "Reserved for future use"},
    {"id": 9, "label": "Reserved for future use"},
    {"id": 10, "label": "Reserved for future use"},
    {"id": 11, "label": "Reserved for future use"},
    {"id": 12, "label": "Reserved for future use"},
    {"id": 13, "label": "Reserved for future use"},
    {"id": 14, "label": "Reserved for future use"},
    {"id": 15, "label": "Reserved for future use"},
    {"id": 16, "label": "Reserved for future use"},
    {"id": 17, "label": "Reserved for future use"},
    {"id": 18, "label": "Reserved for future use"},
    {"id": 19, "label": "Reserved for future use"},
    {"id": 20, "label": "Wing in ground (WIG), all ships of this type"},
    {"id": 21, "label": "Wing in ground (WIG), Hazardous category A"},
    {"id": 22, "label": "Wing in ground (WIG), Hazardous category B"},
    {"id": 23, "label": "Wing in ground (WIG), Hazardous category C"},
    {"id": 24, "label": "Wing in ground (WIG), Hazardous category D"},
    {"id": 25, "label": "Wing in ground (WIG), Reserved for future use"},
    {"id": 26, "label": "Wing in ground (WIG), Reserved for future use"},
    {"id": 27, "label": "Wing in ground (WIG), Reserved for future use"},
    {"id": 28, "label": "Wing in ground (WIG), Reserved for future use"},
    {"id": 29, "label": "Wing in ground (WIG), Reserved for future use"},
    {"id": 30, "label": "Fishing"},
    {"id": 31, "label": "Towing"},
    {"id": 32, "label": "Towing: length exceeds 200m or breadth exceeds 25m"},
    {"id": 33, "label": "Dredging or underwater ops"},
    {"id": 34, "label": "Diving ops"},
    {"id": 35, "label": "Military ops"},
    {"id": 36, "label": "Sailing"},
    {"id": 37, "label": "Pleasure Craft"},
    {"id": 38, "label": "Reserved"},
    {"id": 39, "label": "Reserved"},
    {"id": 40, "label": "High speed craft (HSC), all ships of this type"},
    {"id": 41, "label": "High speed craft (HSC), Hazardous category A"},
    {"id": 42, "label": "High speed craft (HSC), Hazardous category B"},
    {"id": 43, "label": "High speed craft (HSC), Hazardous category C"},
    {"id": 44, "label": "High speed craft (HSC), Hazardous category D"},
    {"id": 45, "label": "High speed craft (HSC), Reserved for future use"},
    {"id": 46, "label": "High speed craft (HSC), Reserved for future use"},
    {"id": 47, "label": "High speed craft (HSC), Reserved for future use"},
    {"id": 48, "label": "High speed craft (HSC), Reserved for future use"},
    {"id": 49, "label": "High speed craft (HSC), No additional information"},
    {"id": 50, "label": "Pilot Vessel"},
    {"id": 51, "label": "Search and Rescue vessel"},
    {"id": 52, "label": "Tug"},
    {"id": 53, "label": "Port Tender"},
    {"id": 54, "label": "Anti-pollution equipment"},
    {"id": 55, "label": "Law Enforcement"},
    {"id": 56, "label": "Spare - Local Vessel"},
    {"id": 57, "label": "Spare - Local Vessel"},
    {"id": 58, "label": "Medical Transport"},
    {"id": 59, "label": "Noncombatant ship according to RR Resolution No. 18"},
    {"id": 60, "label": "Passenger, all ships of this type"},
    {"id": 61, "label": "Passenger, Hazardous category A"},
    {"id": 62, "label": "Passenger, Hazardous category B"},
    {"id": 63, "label": "Passenger, Hazardous category C"},
    {"id": 64, "label": "Passenger, Hazardous category D"},
    {"id": 65, "label": "Passenger, Reserved for future use"},
    {"id": 66, "label": "Passenger, Reserved for future use"},
    {"id": 67, "label": "Passenger, Reserved for future use"},
    {"id": 68, "label": "Passenger, Reserved for future use"},
    {"id": 69, "label": "Passenger, No additional information"},
    {"id": 70, "label": "Cargo, all ships of this type"},
    {"id": 71, "label": "Cargo, Hazardous category A"},
    {"id": 72, "label": "Cargo, Hazardous category B"},
    {"id": 73, "label": "Cargo, Hazardous category C"},
    {"id": 74, "label": "Cargo, Hazardous category D"},
    {"id": 75, "label": "Cargo, Reserved for future use"},
    {"id": 76, "label": "Cargo, Reserved for future use"},
    {"id": 77, "label": "Cargo, Reserved for future use"},
    {"id": 78, "label": "Cargo, Reserved for future use"},
    {"id": 79, "label": "Cargo, No additional information"},
    {"id": 80, "label": "Tanker, all ships of this type"},
    {"id": 81, "label": "Tanker, Hazardous category A"},
    {"id": 82, "label": "Tanker, Hazardous category B"},
    {"id": 83, "label": "Tanker, Hazardous category C"},
    {"id": 84, "label": "Tanker, Hazardous category D"},
    {"id": 85, "label": "Tanker, Reserved for future use"},
    {"id": 86, "label": "Tanker, Reserved for future use"},
    {"id": 87, "label": "Tanker, Reserved for future use"},
    {"id": 88, "label": "Tanker, Reserved for future use"},
    {"id": 89, "label": "Tanker, No additional information"},
    {"id": 90, "label": "Other Type, all ships of this type"},
    {"id": 91, "label": "Other Type, Hazardous category A"},
    {"id": 92, "label": "Other Type, Hazardous category B"},
    {"id": 93, "label": "Other Type, Hazardous category C"},
    {"id": 94, "label": "Other Type, Hazardous category D"},
    {"id": 95, "label": "Other Type, Reserved for future use"},
    {"id": 96, "label": "Other Type, Reserved for future use"},
    {"id": 97, "label": "Other Type, Reserved for future use"},
    {"id": 98, "label": "Other Type, Reserved for future use"},
    {"id": 99, "label": "Other Type, no additional information"}
]

SHIPTYPE_MAP = {item['id']: item['label'] for item in SHIPTYPE_LIST}
